spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pfm}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
      timeout: 7d
